
# jetson-Xavier -------------------
CAM_IP:         "192.168.0.101"
CAM_ID:         "udr"
CAM_PASSWD:     "nvidia"
CAM_PATH :      "/home/udr/workspace/00_Ko/Studio_Prj_Arch2021/LgSwArchCode2021Distv2/LgFaceRecDemoTCP_Jetson_Nano"
# ---------------------------------

CAM_SSH_PORT:   "22"
CAM_TRAIN_DATA_PATH: "faces" 
CAM_TRAIN_DATASET_PATH: "faces/train/datasets/bbt" 
# Commands
CAM_TRAIN_CMD: "bg_train.sh" 
CAM_TEST_RUN_CMD: "bg_DemoWithVideo.sh"
